//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox_Asset_Changer.Properties.LanguageResources.OptionsPageResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roblox_Asset_Changer.Properties.LanguageResources.OptionsPageResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops, tab in development, 
        ///this tab will be available in a future build..
        /// </summary>
        public static string Gblindev {
            get {
                return ResourceManager.GetString("Gblindev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English (Inglés).
        /// </summary>
        public static string LanguageCBen {
            get {
                return ResourceManager.GetString("LanguageCBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish (Español).
        /// </summary>
        public static string LanguageCBesp {
            get {
                return ResourceManager.GetString("LanguageCBesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the app language.
        /// </summary>
        public static string LanguageCBHint {
            get {
                return ResourceManager.GetString("LanguageCBHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string PageHeaderText {
            get {
                return ResourceManager.GetString("PageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current Roblox Directory is:.
        /// </summary>
        public static string RobloxDirectoryCurrentRobloxDirectory {
            get {
                return ResourceManager.GetString("RobloxDirectoryCurrentRobloxDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open the roblox folder.
        /// </summary>
        public static string RobloxDirectoryOpenFolderSelection {
            get {
                return ResourceManager.GetString("RobloxDirectoryOpenFolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the roblox folder.
        /// </summary>
        public static string RobloxDirectorySelectFolder {
            get {
                return ResourceManager.GetString("RobloxDirectorySelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration File.
        /// </summary>
        public static string TabControlConfFileHeader {
            get {
                return ResourceManager.GetString("TabControlConfFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string TabControlLanguageHeader {
            get {
                return ResourceManager.GetString("TabControlLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging options.
        /// </summary>
        public static string TabControlLogHeader {
            get {
                return ResourceManager.GetString("TabControlLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roblox Directory.
        /// </summary>
        public static string TabControlRobloxDirectoryHeader {
            get {
                return ResourceManager.GetString("TabControlRobloxDirectoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Interface.
        /// </summary>
        public static string TabControlUIHeader {
            get {
                return ResourceManager.GetString("TabControlUIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blue.
        /// </summary>
        public static string UIAccentCBblue {
            get {
                return ResourceManager.GetString("UIAccentCBblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        public static string UIAccentCBdefault {
            get {
                return ResourceManager.GetString("UIAccentCBdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Green.
        /// </summary>
        public static string UIAccentCBgreen {
            get {
                return ResourceManager.GetString("UIAccentCBgreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string UIAccentCBred {
            get {
                return ResourceManager.GetString("UIAccentCBred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yellow.
        /// </summary>
        public static string UIAccentCByellow {
            get {
                return ResourceManager.GetString("UIAccentCByellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark Theme On.
        /// </summary>
        public static string UIdarkThemeon {
            get {
                return ResourceManager.GetString("UIdarkThemeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light Theme On.
        /// </summary>
        public static string UIlightThemeon {
            get {
                return ResourceManager.GetString("UIlightThemeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primary Accent Color.
        /// </summary>
        public static string UIPrimaryAccentText {
            get {
                return ResourceManager.GetString("UIPrimaryAccentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secondary Accent Color.
        /// </summary>
        public static string UISecondaryAccentText {
            get {
                return ResourceManager.GetString("UISecondaryAccentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change app theme.
        /// </summary>
        public static string UIThemeSw {
            get {
                return ResourceManager.GetString("UIThemeSw", resourceCulture);
            }
        }
    }
}
