//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox_Asset_Changer.Properties.LanguageResources.ShellResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roblox_Asset_Changer.Properties.LanguageResources.ShellResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let me take a look.
        /// </summary>
        public static string behindCodeAssetsPromptCloseBtn {
            get {
                return ResourceManager.GetString("behindCodeAssetsPromptCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Looks like you are trying to modify some asset without having the Roblox Folder configured, maybe set it up and we could work with it. .
        /// </summary>
        public static string behindCodeAssetsPromptContent {
            get {
                return ResourceManager.GetString("behindCodeAssetsPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Okay, I&apos;ll see the options page.
        /// </summary>
        public static string behindCodeAssetsPromptPrimBtn {
            get {
                return ResourceManager.GetString("behindCodeAssetsPromptPrimBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roblox Folder not detected.
        /// </summary>
        public static string behindCodeAssetsPromptTitle {
            get {
                return ResourceManager.GetString("behindCodeAssetsPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string listViewAboutHeader {
            get {
                return ResourceManager.GetString("listViewAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursor.
        /// </summary>
        public static string listViewCursorHeader {
            get {
                return ResourceManager.GetString("listViewCursorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Face.
        /// </summary>
        public static string listViewFaceHeader {
            get {
                return ResourceManager.GetString("listViewFaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string listViewHomeHeader {
            get {
                return ResourceManager.GetString("listViewHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading Game.
        /// </summary>
        public static string listViewLoadingGameHeader {
            get {
                return ResourceManager.GetString("listViewLoadingGameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string listViewOptionsHeader {
            get {
                return ResourceManager.GetString("listViewOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roblox Menu.
        /// </summary>
        public static string listViewRobloxMenuHeader {
            get {
                return ResourceManager.GetString("listViewRobloxMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sounds.
        /// </summary>
        public static string listViewSoundsHeader {
            get {
                return ResourceManager.GetString("listViewSoundsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Bar.
        /// </summary>
        public static string listViewTopBarHeader {
            get {
                return ResourceManager.GetString("listViewTopBarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string listViewUpdateHeader {
            get {
                return ResourceManager.GetString("listViewUpdateHeader", resourceCulture);
            }
        }
    }
}
